### ISSUE TITLE
Http response at 400 or 500 level, http status code: 503

### ISSUE THREAD

**Issue by preland** [haveno-dex/haveno-ts#287]
Whenever attempting to run any test, it will fail all with the above error.

Changing the stopOnFailure value back to true from false does not change the behavior in any visible way.

**Comment by woodser** [comment]
I'd first try killing all Java and Monero processes, then restart monerod1, monerod2, monero-wallet-rpc, the seed node, and envoy proxy, then try again.

**Comment by woodser** [comment]
Quite likely this issue was related to using a version of docker past 4.26.1.

I've discovered that the tests fail with this error ("Http response at 400 or 500 level, http status code: 503") if using the latest docker.

**Comment by woodser** [comment]
Opened an issue to update to the latest version of docker with 2 XMR bounty: https://github.com/haveno-dex/haveno-ts/issues/308

**Comment by woodser** [comment]
Issue is resolved by @mainnet-pat in https://github.com/haveno-dex/haveno-ts/pull/315, by updating the instructions to use envoy separately from docker, and adding local envoy config.
