### ISSUE TITLE
Contribute design assets?

### ISSUE THREAD

**Issue by sirjamesgray** [haveno-dex/haveno-ts#52]
Are there any Figma or Sketch files for the UI? 

I'm a Product Designer and would love to help contribute to the design direction. 

Thanks

**Comment by woodser** [comment]
Yes, the current design is here: https://www.figma.com/file/ijVTy2RIF8j36LF5y2sRtt/Haveno-Product-Design?node-id=856%3A5172

**Comment by erciccione** [comment]
The dedicated repo can be also used: https://github.com/haveno-dex/haveno-design
